FROM openjdk:8-jre

ENV PATH $SPARK_DIR/bin:$PATH
ENV SPARK_VERSION=3.1.1
ENV SPARK_DIR=/opt/spark
ENV PATH $SPARK_DIR/bin:$PATH
ARG TXT=dataset/cockatiel.csv

RUN apt update && apt -y install bash python3 python3-pip

RUN pip3 install pyspark
# Create Sym Link 
ADD setup/spark-${SPARK_VERSION}-bin-hadoop2.7.tgz /opt
ADD ${TXT} /opt/tap/spark/dataset/
# Add Python Code
ADD code/wordcount.py  /opt/tap/
# Add Spark Manager
ADD spark-manager-wc.sh $SPARK_DIR/bin/spark-manager-wc


RUN ln -s /opt/spark-${SPARK_VERSION}-bin-hadoop2.7 ${SPARK_DIR} 

WORKDIR ${SPARK_DIR}
ENTRYPOINT [ "spark-manager-wc" ] 